---
name: sabc-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.14
  - ipykernel # vscode
  - ipywidgets # other jupyter func.
  - rich # nice logging
  - nodejs
  - uv
  - emcee
  - numpy
  - scipy
  - numba
  - matplotlib
  - tqdm
  - pytest
  - jupytext
  - pip:
    - scalene
