---
name: sabc-dev
extends:
  - file: environment.sabc.yml
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ipykernel
  - ipywidgets
  - rich
  - tqdm
  - nodejs
  - uv
  - ty
  - ruff
  - emcee
  - matplotlib
  - pytest
  - pytest-cov
  - jupytext
  - pip:
    - scalene
